### ISSUE TITLE
Create egressgateway usage not update 

### ISSUE THREAD

**Issue by lou-lan** [spidernet-io/egressgateway#1309]
Create egressgateway, the egressgateway node selector not match any node, the egressgateway CR not update IPPool usage.

```yaml
apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressGateway
metadata:
  annotations:
    description: ""
  name: egw2
spec:
  ippools:
    ipv4:
    - 10.6.92.5/24
  nodeSelector:
    selector:
      matchLabels:
        egress: "true"
```

```shell
NAME            IPV4DEFAULTEIP   IPV6DEFAULTEIP   CLUSTERDEFAULT   IPV4TOTAL   IPV4FREE   IPV6TOTAL   IPV6FREE
egw2             10.6.92.188                                        
```
