### ISSUE TITLE
Use multiple egress policies in a namespace

### ISSUE THREAD

**Issue by KlettIT** [spidernet-io/egressgateway#1574]
0.6.0

**Describe the bug**
Not able to use multiple egress policies in a namespace

**How To Reproduce**

Define pool
```
apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressGateway
metadata:
  name: egress-pool-monitoring
spec:
  ippools:
    ipv4:
    - "10.195.30.21-10.195.30.23"
  nodeSelector:
    selector:
      matchLabels:
        egressgateway: "true"
```

policies:

```
apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressPolicy
metadata:
 name: vmagent
 namespace: monitoring
spec:
 egressGatewayName: egress-pool-monitoring
 egressIP:
   ipv4: 10.195.30.21
 appliedTo:
  podSelector:
   matchLabels:
    app.kubernetes.io/name: "vmagent"
---

apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressPolicy
metadata:
 name: blackbox-exporter
 namespace: monitoring
spec:
 egressGatewayName: egress-pool-monitoring
 egressIP:
   ipv4: 10.195.30.22
 appliedTo:
  podSelector:
   matchLabels:
    app.kubernetes.io/name: "prometheus-blackbox-exporter"
---

apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressPolicy
metadata:
 name: snmp-exporter
 namespace: monitoring
spec:
 egressGatewayName: egress-pool-monitoring
 egressIP:
   ipv4: 10.195.30.23
 appliedTo:
  podSelector:
   matchLabels:
    app.kubernetes.io/name: "prometheus-snmp-exporter"
```

**Expected behavior**
It should be possible to use multiple egress policies in a namespace.

**Screenshots and log**

![image](https://github.com/user-attachments/assets/180dfdf5-80a1-456f-9a40-0030649db678)

**Additional context**
Honestly i am not sure if this is by design or a bug....
