### ISSUE TITLE
 Cilium native mode, The pod configured with egressgateway accesses the pod in the cluster, also using egressgateway

### ISSUE THREAD

**Issue by changluyi** [spidernet-io/egressgateway#1715]
**Describe the version**
v0.6.3

**Describe the bug**
cilium native mode，cilium install command
```
cilium install --wait --version 1.18.0-pre.3 \
    --set enable-ipv4=true \
    --set ipv4NativeRoutingCIDR=10.3.0.0/16 \
    --set autoDirectNodeRoutes=true \
    --set routingMode="native" \
    --set bpf.masquerade=false \
    --set ipam.mode=cluster-pool \
    --set ipam.operator.clusterPoolIPv4PodCIDRList={10.3.0.0/16} \
    --set ipam.operator.clusterPoolIPv4MaskSize=24
```
egressgateway install command
```
helm install egressgateway egressgateway/egressgateway \
	  -n kube-system \
		--set feature.tunnelIpv4Subnet="192.200.0.1/16" \
		--wait --debug
```

egressgateway config
```
cat <<EOF | kubectl apply -f -
apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressGateway
metadata:
  name: default
spec:
  ippools:
    ipv4:
    - "172.22.0.100-172.22.0.110"
  nodeSelector:
    selector:
      matchLabels:
        egressgateway: "true"
EOF
```
```
cat <<EOF | kubectl apply -f -
apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressPolicy
metadata:
 name: test
 namespace: cillium-redhat-1
spec:
 egressGatewayName: default
 appliedTo:
  podSelector:
   matchLabels:
    service.cpaas.io/name: "deployment-qaimages"
EOF
```

Then I found that the pods labeled service.cpaas.io/name: "deployment-qaimages" were unable to access traffic within the cluster.

Packet capture shows that the traffic is going through the egress.vxlan interface:

![Image](https://github.com/user-attachments/assets/db2a3cdb-a83f-449e-b0db-9ef2de4b8d29)

**How To Reproduce**
Steps to reproduce the issue:

**Expected behavior**

**Screenshots and log**
If applicable, add screenshots and log to help explain your problem.

**Additional context**

**Comment by lou-lan** [comment]
Which service name or IP address are you trying to access? On the node where your pod is running, you can run `ipset list` to check whether `egress-cluster-cidr-ipv4` includes your internal IP address.

**Comment by changluyi** [comment]
![Image](https://github.com/user-attachments/assets/b826ee57-77d4-4dce-b1b7-210655f308ed)

![Image](https://github.com/user-attachments/assets/84b7780c-2670-4d60-8ba0-8a8e8a47a957)


![Image](https://github.com/user-attachments/assets/bbcb3cfd-3b3e-4e05-99ea-c17f495741d3)

**Comment by changluyi** [comment]
it seems pod cidr not in the ipset `egress-cluster-cidr-ipv4`

**Comment by lou-lan** [comment]
Yes, the `10.3.0.0/16 `range was not extracted into the CIDR list — this appears to be a bug and needs to be fixed.
Currently, the only workaround is to manually specify the destSubnet.

apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressPolicy
metadata:
  namespace: "default"
  name: "policy-test"
spec:
...
  destSubnet:
    - "10.6.1.92/32"
    - "fd00::92/128"
...

**Comment by changluyi** [comment]
> Yes, the `10.3.0.0/16 `range was not extracted into the CIDR list — this appears to be a bug and needs to be fixed. Currently, the only workaround is to manually specify the destSubnet.
> 
> apiVersion: egressgateway.spidernet.io/v1beta1
> kind: EgressPolicy
> metadata:
>   namespace: "default"
>   name: "policy-test"
> spec:
> ...
>   destSubnet:
>     - "10.6.1.92/32"
>     - "fd00::92/128"
> ...

it seems not work , but I try this config below solve this problem:

```
apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressClusterInfo
metadata:
  name: default
spec:
  extraCidr:
  - 10.3.0.0/16
```
