### ISSUE TITLE
gateway status not update

### ISSUE THREAD

**Issue by lou-lan** [spidernet-io/egressgateway#397]
version: `v0.2.0-rc0`

Reproduction step:
1. create `egressgateway` and `egressspolicy`
2. `kubectl label node worker01 egress=true`
3. gateway status not update

```yaml
apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressGateway
metadata:
  name: "egressgateway"
spec:
  ranges:
    ipv4:
      - "10.5.212.151"
      - "10.5.212.132"
    ipv6:
      - "fd00:10:5:212::151"
      - "fd00:10:5:212::152"
  nodeSelector:
    selector:
      matchLabels:
        egress: "true"
---
apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressPolicy
metadata:
  name: fake-app
spec:
  egressGatewayName: egressgateway
  appliedTo:
    podSelector:
      matchLabels:
        test: test
  destSubnet:
    - 10.6.1.92/32
    - fd00::92/128
    - 172.30.40.0/21
---
apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressPolicy
metadata:
  name: fake-app-2
spec:
  egressGatewayName: egressgateway
  appliedTo:
    podSelector:
      matchLabels:
        test: test
  destSubnet:
    - 10.6.1.92/32
    - fd00::92/128
    - 172.30.40.0/21
```
