### ISSUE TITLE
[ doc ] The `Check the status` step in the installation document is incorrect

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/egressgateway#964]
When we create the egressgateway
```
cat <<EOF | kubectl apply -f -
apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressGateway
metadata:
  name: default
spec:
  ippools:
    ipv4:
    - "172.22.0.100-172.22.0.110"
  nodeSelector:
    selector:
      matchLabels:
        egressgateway: "true"
EOF
```
But the yaml of the egressgateway is 
```
$ kubectl get EgressGateway default -o yaml
apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressGateway
metadata:
  name: default
  uid: 7ce835e2-2075-4d26-ba63-eacd841aadfe
spec:
  clusterDefault: true
  ippools:
    ipv4:
    - 172.22.0.100-172.22.0.110
    ipv4DefaultEIP: 172.22.0.110
  nodeSelector:
    selector:
      matchLabels:
        egressgateway: "true"
status:
  nodeList:
  - name: egressgateway-worker1
    status: Ready
  - name: egressgateway-worker2
    status: Ready
```

The field `clusterDefault: true` is not expected here
